spring.application.name=shopsphere
spring.datasource.url=jdbc:mysql://localhost:3306/shopsphere
spring.datasource.username=root
spring.datasource.password=Mouni@000

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.thyme-leaf.cache=false